### ISSUE TITLE
Set profile user story and label texts issues

### ISSUE THREAD

**Issue by Jeffardio** [softeng-team4/HikeTracker_04#14]
According to US no. 33 (Set profile), only an hiker can set his profile in order to get recommended hikes. So please, remove this feature for a user that is logged in as a local guide, hut worker or platform manager. 

Another minor issue: some buttons and labels have texts that do not start with a capital letter.

**Comment by francescofiorella** [comment]
The profile issue, along with the wrong labels, have been fixed.
Thank you for your feedback!
